# Generated by Django 2.1.7 on 2019-05-21 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(choices=[('T-Shirts', (('shirt_size', 'Shirt Size'), ('shirt_color', 'Shirt Color'), ('shirt_fabric', 'Shirt Fabric'))), ('Glasses', (('glass_type', 'Glass Type'), ('glass_size', 'Glass Size'))), ('Shoes', (('shoe_type', 'Shoe Type'), ('shoe_size', 'Shoe Size'))), ('Other', ())], default='Default', max_length=50)),
                ('value', models.CharField(max_length=50)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Product')),
            ],
        ),
    ]
